### ISSUE TITLE
Improve knowledge about rugby union

### ISSUE THREAD

**Issue by Bruce0C** [Bruce0C/Rugby-Buff#1]
**User story**
As a new fan of the rugby union, i would like to know more about the sports history. I'd also like to know more about current tournaments I could watch and teams I can support. 

**Acceptance criteria**

- [x] History section on the home page.
- [x] Tournaments section on the home page, showing when the events are held and which teams take part.
- [x] Top-ten world ranking teams section shown as a table. table will clarify each teams region and stadiums.

**Tasks**

- [x] Add HTML three sections to the home page dedicated to rugby union history, tournaments and top teams.
- [x] Style the sections to make them responsive to changes in screen size.
- [ ] Fill each section with brief overview of the topic.
