### ISSUE TITLE
How to play rugby

### ISSUE THREAD

**Issue by Bruce0C** [Bruce0C/Rugby-Buff#2]
**User story **
As a new player and supporter to rugby union, I want to understand ho the game is played and what the markings on a rugby pitch mean.

**Acceptance criteria **

- [ ] The how to play page include sections on the pitch, officials, playing positions and how to position.
- [ ] The sections are responsive and look good on all main device sizes.
- [ ] Officials and how to position sections include relevant images. 
- [ ] There is a table simplifying each position on the team. 

**Tasks**

- [ ] Add HTML sections for pitch, officials, playing positions and how to position.
- [ ] Make sections responsive.
- [ ] Add images to the officials and how to position sections.
- [ ] Add table to positions section.
