### ISSUE TITLE
Understanding the rules

### ISSUE THREAD

**Issue by Bruce0C** [Bruce0C/Rugby-Buff#3]
**User story**
As a player and spectator i would like to understand the rules and the reasons for the referee's decisions. 

**Acceptance criteria**

- [ ] The laws page includes sections for the different states of play and the card system 
- [ ] The sections are styled in a way that helps the user understand the information.
- [ ] Each section is responsive to screen size 

**Tasks**

- [ ] Add HTML for card-system, open play, set play, sportsmanship and ethos. 
- [ ] Make sections responsive to device sizes .
- [ ] Style the card-system section using the respective card's colour as the sections background.
