### ISSUE TITLE
Playing kit and equipment

### ISSUE THREAD

**Issue by Bruce0C** [Bruce0C/Rugby-Buff#4]
**User story**
As a new player and supporter I want to know what i need to wear to take part in a rugby game and what other equipment will be used on the pitch to host a game. 

**Acceptance criteria**

- [ ] Sections on equipment and players kit.
- [ ] Images showing what each item should look like.
- [ ] Brief explanation on each item and why it is necessary for the game.

**Task**

- [ ] Add HTML sections for players kit and equipment needed to play the game
- [ ] Make the sections responsive to device size 
- [ ] Add relevant images on each section
